# Generated by Django 4.0.4 on 2022-05-30 17:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, max_length=500, null=True)),
                ('enableChat', models.BooleanField(default=True)),
                ('user', models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Profil',
                'verbose_name_plural': 'Profile',
            },
        ),
        migrations.CreateModel(
            name='Annonce',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titel', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=40)),
                ('straße', models.CharField(blank=True, max_length=40, null=True)),
                ('hausnummer', models.PositiveIntegerField(blank=True, null=True)),
                ('stadt', models.CharField(blank=True, max_length=20, null=True)),
                ('postleitzahl', models.PositiveIntegerField(blank=True, null=True)),
                ('kontakt', models.CharField(max_length=40)),
                ('beschreibung', models.TextField()),
                ('date', models.DateField()),
                ('nachricht', models.TextField(blank=True, null=True)),
                ('author', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Annonce',
                'verbose_name_plural': 'Annoncen',
            },
        ),
    ]
