# Generated by Django 4.0.4 on 2022-05-30 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annoncen', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annonce',
            name='name',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
