# Generated by Django 4.0.4 on 2022-06-03 10:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('annoncen', '0002_alter_annonce_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bild',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bild', models.ImageField(upload_to='annoncen')),
                ('annonce', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='annoncen.annonce')),
            ],
        ),
    ]
