# Generated by Django 4.0.4 on 2022-06-05 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annoncen', '0002_alter_annonce_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='annonce',
            name='typ',
            field=models.BooleanField(default=0),
        ),
    ]
