# Generated by Django 4.0.4 on 2022-06-08 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annoncen', '0003_bild'),
    ]

    operations = [
        migrations.AddField(
            model_name='bild',
            name='is_cover_image',
            field=models.BooleanField(default=False),
        ),
    ]
