# Generated by Django 4.0.4 on 2022-06-06 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annoncen', '0003_annonce_typ'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='hausnummer',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='postleitzahl',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='stadt',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='straße',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
