# Generated by Django 4.0.4 on 2022-06-07 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annoncen', '0004_profile_hausnummer_profile_postleitzahl_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kategorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
            ],
        ),
        migrations.AddField(
            model_name='annonce',
            name='kategorie',
            field=models.CharField(default='unkategorisiert', max_length=40),
        ),
    ]
