# Generated by Django 4.0.4 on 2022-06-08 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('annoncen', '0004_bild_is_cover_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bild',
            old_name='is_cover_image',
            new_name='isCoverImage',
        ),
    ]
