# Generated by Django 4.0.4 on 2022-06-08 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('annoncen', '0004_profile_hausnummer_profile_postleitzahl_and_more'),
        ('annoncen', '0005_rename_is_cover_image_bild_iscoverimage'),
    ]

    operations = [
    ]
