# Generated by Django 4.0.4 on 2022-06-08 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annoncen', '0006_merge_20220608_1502'),
    ]

    operations = [
        migrations.AddField(
            model_name='annonce',
            name='height',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='annonce',
            name='length',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='annonce',
            name='width',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
