# Generated by Django 4.0.4 on 2022-06-08 16:52

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('annoncen', '0007_annonce_height_annonce_length_annonce_width'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annonce',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 8, 16, 52, 7, 584478, tzinfo=utc)),
        ),
    ]
