# Generated by Django 4.0.4 on 2022-06-08 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annoncen', '0008_alter_annonce_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annonce',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
