# Generated by Django 4.0.4 on 2022-06-12 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('annoncen', '0005_kategorie_annonce_kategorie'),
        ('annoncen', '0010_annonce_available_until'),
    ]

    operations = [
    ]
