# Generated by Django 4.0.4 on 2022-06-12 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('annoncen', '0011_merge_20220612_1603'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='kategorie',
            options={'verbose_name': 'Kategorie', 'verbose_name_plural': 'Kategorien'},
        ),
    ]
