# Generated by Django 4.0.4 on 2022-06-12 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annoncen', '0011_merge_20220612_1917'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='kategorie',
            options={'verbose_name': 'Kategorie', 'verbose_name_plural': 'Kategorien'},
        ),
        migrations.RemoveField(
            model_name='annonce',
            name='kategorie',
        ),
        migrations.AddField(
            model_name='annonce',
            name='kategorie',
            field=models.ManyToManyField(blank=True, default=None, null=True, to='annoncen.kategorie'),
        ),
    ]
