# Generated by Django 4.0.4 on 2022-06-14 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('annoncen', '0012_alter_kategorie_options'),
        ('annoncen', '0016_annonce_latitude_annonce_longitude_and_more'),
    ]

    operations = [
    ]
