# Generated by Django 4.0.4 on 2022-06-18 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annoncen', '0017_merge_20220614_1932'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='searchRadius',
            field=models.PositiveIntegerField(default=20),
        ),
    ]
