# Generated by Django 4.0.4 on 2022-06-22 01:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annoncen', '0021_alter_annonce_available_until'),
    ]

    operations = [
        migrations.AddField(
            model_name='annonce',
            name='adresszusatz',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='adresszusatz',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='annonce',
            name='available_until',
            field=models.DateField(default=datetime.date(2022, 9, 22)),
        ),
    ]
