# Generated by Django 4.0.4 on 2022-07-02 22:23

import datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('annoncen', '0023_annonce_reserviert_annonce_reserviert_von_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='annonce',
            name='gemerkt',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='annonce',
            name='gemerkt_von',
            field=models.ManyToManyField(blank=True, default=None, related_name='merker', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='annonce',
            name='available_until',
            field=models.DateField(default=datetime.date(2022, 10, 3)),
        ),
    ]
