# Generated by Django 4.0.4 on 2022-07-11 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('annoncen', '0024_alter_annonce_available_until'),
        ('annoncen', '0024_annonce_gemerkt_annonce_gemerkt_von_and_more'),
    ]

    operations = [
    ]
