# Generated by Django 4.0.4 on 2022-07-19 22:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annoncen', '0025_merge_20220711_2154'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='nachname',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='profilbild',
            field=models.ImageField(blank=True, null=True, upload_to='profilbilder'),
        ),
        migrations.AddField(
            model_name='profile',
            name='vorname',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='annonce',
            name='available_until',
            field=models.DateField(default=datetime.date(2022, 10, 20)),
        ),
    ]
